# Generated by Django 5.0.7 on 2024-07-16 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adminapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='train',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='train',
            name='schedule',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Every two days', 'Every two days')], default='Daily', max_length=30),
        ),
    ]
