# Generated by Django 5.0.7 on 2024-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_section_train_sections_alter_train_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='section',
            field=models.CharField(choices=[('All', 'All'), ('Sleeper', 'Sleeper'), ('Upper Berth', 'Upper Berth'), ('Lower Berth', 'Lower Berth'), ('AC Coach', 'AC Coach')], default='All', max_length=20),
        ),
    ]
