# Generated by Django 5.0.7 on 2024-07-16 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('train_id', models.IntegerField()),
                ('section', models.CharField(max_length=50)),
                ('seat_number', models.IntegerField()),
                ('train_arrival', models.DateTimeField()),
                ('train_departure', models.DateTimeField()),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Booked', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
