# Generated by Django 5.0.7 on 2024-07-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.CharField(max_length=50),
        ),
    ]
