# Generated by Django 5.0.7 on 2024-07-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_train_arrival_time_alter_train_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
