# Generated by Django 5.0.7 on 2024-07-16 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_train_arrival_time_alter_train_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
